apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  namespace: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins-app-container
          image: mnaggar3396/jenkins-node-app
          ports:
            - name: httpport
              containerPort: 3000
      